// Mocks generated by Mockito 5.0.12 from annotations
// in deall/test/retailer/products/application/add_product_form_notifier_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;
import 'dart:io' as _i9;

import 'package:dartz/dartz.dart' as _i2;
import 'package:deall/auth/application/app_user.dart' as _i11;
import 'package:deall/auth/application/auth_failure.dart' as _i12;
import 'package:deall/auth/infrastructure/auth_repository.dart' as _i10;
import 'package:deall/core/application/image_picking_failure.dart' as _i8;
import 'package:deall/core/application/product/product.dart' as _i6;
import 'package:deall/core/application/retailer/retailer.dart' as _i13;
import 'package:deall/core/infrastructure/firestore_failures.dart' as _i5;
import 'package:deall/core/infrastructure/image_picking_repository.dart' as _i7;
import 'package:deall/retailer/product/infrastructure/product_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeEither<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i3.ProductRepository {
  MockProductRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.FirestoreFailures, List<_i6.Product>>>
      getProductList(String? retailerId) => (super.noSuchMethod(
          Invocation.method(#getProductList, [retailerId]),
          returnValue: Future<
                  _i2.Either<_i5.FirestoreFailures, List<_i6.Product>>>.value(
              _FakeEither<_i5.FirestoreFailures, List<_i6.Product>>())) as _i4
          .Future<_i2.Either<_i5.FirestoreFailures, List<_i6.Product>>>);
  @override
  _i4.Stream<_i2.Either<_i5.FirestoreFailures, List<_i6.Product>>>
      getProductStream() => (super.noSuchMethod(
              Invocation.method(#getProductStream, []),
              returnValue: Stream<
                  _i2.Either<_i5.FirestoreFailures, List<_i6.Product>>>.empty())
          as _i4.Stream<_i2.Either<_i5.FirestoreFailures, List<_i6.Product>>>);
  @override
  String generateNewProductId(String? uid) =>
      (super.noSuchMethod(Invocation.method(#generateNewProductId, [uid]),
          returnValue: '') as String);
  @override
  _i4.Future<_i2.Either<_i5.FirestoreFailures, void>> addProduct(
          _i6.Product? newProduct, String? uid) =>
      (super.noSuchMethod(Invocation.method(#addProduct, [newProduct, uid]),
          returnValue: Future<_i2.Either<_i5.FirestoreFailures, void>>.value(
              _FakeEither<_i5.FirestoreFailures, void>())) as _i4
          .Future<_i2.Either<_i5.FirestoreFailures, void>>);
  @override
  _i4.Future<_i2.Either<_i5.FirestoreFailures, _i2.Unit>> updateProduct(
          _i6.Product? product) =>
      (super.noSuchMethod(Invocation.method(#updateProduct, [product]),
              returnValue:
                  Future<_i2.Either<_i5.FirestoreFailures, _i2.Unit>>.value(
                      _FakeEither<_i5.FirestoreFailures, _i2.Unit>()))
          as _i4.Future<_i2.Either<_i5.FirestoreFailures, _i2.Unit>>);
  @override
  _i4.Future<_i2.Either<_i5.FirestoreFailures, _i2.Unit>> deleteProduct(
          _i6.Product? product) =>
      (super.noSuchMethod(Invocation.method(#deleteProduct, [product]),
              returnValue:
                  Future<_i2.Either<_i5.FirestoreFailures, _i2.Unit>>.value(
                      _FakeEither<_i5.FirestoreFailures, _i2.Unit>()))
          as _i4.Future<_i2.Either<_i5.FirestoreFailures, _i2.Unit>>);
  @override
  _i4.Future<_i2.Either<_i5.FirestoreFailures, _i2.Unit>> updateProductList(
          List<_i6.Product>? productList) =>
      (super.noSuchMethod(Invocation.method(#updateProductList, [productList]),
              returnValue:
                  Future<_i2.Either<_i5.FirestoreFailures, _i2.Unit>>.value(
                      _FakeEither<_i5.FirestoreFailures, _i2.Unit>()))
          as _i4.Future<_i2.Either<_i5.FirestoreFailures, _i2.Unit>>);
}

/// A class which mocks [ImagePickingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockImagePickingRepository extends _i1.Mock
    implements _i7.ImagePickingRepository {
  MockImagePickingRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i8.ImagePickingFailure, _i9.File>> pickImage() =>
      (super
          .noSuchMethod(Invocation.method(#pickImage, []),
              returnValue:
                  Future<_i2.Either<_i8.ImagePickingFailure, _i9.File>>.value(
                      _FakeEither<_i8.ImagePickingFailure, _i9.File>())) as _i4
          .Future<_i2.Either<_i8.ImagePickingFailure, _i9.File>>);
  @override
  _i4.Future<_i2.Either<_i8.ImagePickingFailure, String>>
      uploadShopLogoToCloudStorage({String? userId, _i9.File? file}) => (super
              .noSuchMethod(
                  Invocation.method(#uploadShopLogoToCloudStorage, [],
                      {#userId: userId, #file: file}),
                  returnValue:
                      Future<_i2.Either<_i8.ImagePickingFailure, String>>.value(
                          _FakeEither<_i8.ImagePickingFailure, String>()))
          as _i4.Future<_i2.Either<_i8.ImagePickingFailure, String>>);
  @override
  _i4.Future<_i2.Either<_i8.ImagePickingFailure, String>>
      uploadProductImageToCloudStorage(
              {String? userId, _i9.File? file, String? productId}) =>
          (super.noSuchMethod(
                  Invocation.method(#uploadProductImageToCloudStorage, [],
                      {#userId: userId, #file: file, #productId: productId}),
                  returnValue:
                      Future<_i2.Either<_i8.ImagePickingFailure, String>>.value(
                          _FakeEither<_i8.ImagePickingFailure, String>()))
              as _i4.Future<_i2.Either<_i8.ImagePickingFailure, String>>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i10.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i11.AppUser?> getFirebaseUser() => (super.noSuchMethod(
      Invocation.method(#getFirebaseUser, []),
      returnValue: Future<_i11.AppUser?>.value()) as _i4.Future<_i11.AppUser?>);
  @override
  String getUserId() =>
      (super.noSuchMethod(Invocation.method(#getUserId, []), returnValue: '')
          as String);
  @override
  _i4.Future<_i2.Either<_i12.AuthFailure, _i11.AppUser>> signIn(
          {String? email, String? password}) =>
      (super.noSuchMethod(
          Invocation.method(#signIn, [], {#email: email, #password: password}),
          returnValue: Future<_i2.Either<_i12.AuthFailure, _i11.AppUser>>.value(
              _FakeEither<_i12.AuthFailure, _i11.AppUser>())) as _i4
          .Future<_i2.Either<_i12.AuthFailure, _i11.AppUser>>);
  @override
  _i4.Future<_i2.Either<_i12.AuthFailure, _i2.Unit>> consumerSignUp(
          {String? email, String? password}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #consumerSignUp, [], {#email: email, #password: password}),
              returnValue: Future<_i2.Either<_i12.AuthFailure, _i2.Unit>>.value(
                  _FakeEither<_i12.AuthFailure, _i2.Unit>()))
          as _i4.Future<_i2.Either<_i12.AuthFailure, _i2.Unit>>);
  @override
  _i4.Future<_i2.Either<_i12.AuthFailure, _i2.Unit>> retailerSignUp(
          {String? email,
          String? password,
          _i13.Retailer? retailer,
          _i9.File? imageFile}) =>
      (super.noSuchMethod(
              Invocation.method(#retailerSignUp, [], {
                #email: email,
                #password: password,
                #retailer: retailer,
                #imageFile: imageFile
              }),
              returnValue: Future<_i2.Either<_i12.AuthFailure, _i2.Unit>>.value(
                  _FakeEither<_i12.AuthFailure, _i2.Unit>()))
          as _i4.Future<_i2.Either<_i12.AuthFailure, _i2.Unit>>);
  @override
  _i4.Future<_i2.Either<_i12.AuthFailure, _i2.Unit>> signOut() =>
      (super.noSuchMethod(Invocation.method(#signOut, []),
              returnValue: Future<_i2.Either<_i12.AuthFailure, _i2.Unit>>.value(
                  _FakeEither<_i12.AuthFailure, _i2.Unit>()))
          as _i4.Future<_i2.Either<_i12.AuthFailure, _i2.Unit>>);
}
