// Mocks generated by Mockito 5.0.12 from annotations
// in deall/test/consumer/application/retailer_list_notifier_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i4;
import 'package:deall/consumer/application/retailer_list_state.dart' as _i8;
import 'package:deall/consumer/infrastructure/firestore_failures.dart' as _i7;
import 'package:deall/consumer/infrastructure/retailer_list_repository.dart'
    as _i5;
import 'package:deall/core/application/retailer.dart' as _i2;
import 'package:deall/core/infrastructure/retailer_dto.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _Fake$RetailerCopyWith<$Res> extends _i1.Fake
    implements _i2.$RetailerCopyWith<$Res> {}

class _Fake$RetailerDTOCopyWith<$Res> extends _i1.Fake
    implements _i3.$RetailerDTOCopyWith<$Res> {}

class _FakeRetailer extends _i1.Fake implements _i2.Retailer {}

class _FakeEither<L, R> extends _i1.Fake implements _i4.Either<L, R> {}

/// A class which mocks [Retailer].
///
/// See the documentation for Mockito's code generation for more information.
class MockRetailer extends _i1.Mock implements _i2.Retailer {
  MockRetailer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name =>
      (super.noSuchMethod(Invocation.getter(#name), returnValue: '') as String);
  @override
  String get block =>
      (super.noSuchMethod(Invocation.getter(#block), returnValue: '')
          as String);
  @override
  String get street =>
      (super.noSuchMethod(Invocation.getter(#street), returnValue: '')
          as String);
  @override
  String get unit =>
      (super.noSuchMethod(Invocation.getter(#unit), returnValue: '') as String);
  @override
  String get postalCode =>
      (super.noSuchMethod(Invocation.getter(#postalCode), returnValue: '')
          as String);
  @override
  String get operatingHours =>
      (super.noSuchMethod(Invocation.getter(#operatingHours), returnValue: '')
          as String);
  @override
  bool get visibility =>
      (super.noSuchMethod(Invocation.getter(#visibility), returnValue: false)
          as bool);
  @override
  _i2.$RetailerCopyWith<_i2.Retailer> get copyWith =>
      (super.noSuchMethod(Invocation.getter(#copyWith),
              returnValue: _Fake$RetailerCopyWith<_i2.Retailer>())
          as _i2.$RetailerCopyWith<_i2.Retailer>);
  @override
  String addressLine() =>
      (super.noSuchMethod(Invocation.method(#addressLine, []), returnValue: '')
          as String);
}

/// A class which mocks [RetailerDTO].
///
/// See the documentation for Mockito's code generation for more information.
class MockRetailerDTO extends _i1.Mock implements _i3.RetailerDTO {
  MockRetailerDTO() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name =>
      (super.noSuchMethod(Invocation.getter(#name), returnValue: '') as String);
  @override
  String get block =>
      (super.noSuchMethod(Invocation.getter(#block), returnValue: '')
          as String);
  @override
  String get street =>
      (super.noSuchMethod(Invocation.getter(#street), returnValue: '')
          as String);
  @override
  String get unit =>
      (super.noSuchMethod(Invocation.getter(#unit), returnValue: '') as String);
  @override
  String get postalCode =>
      (super.noSuchMethod(Invocation.getter(#postalCode), returnValue: '')
          as String);
  @override
  String get operatingHours =>
      (super.noSuchMethod(Invocation.getter(#operatingHours), returnValue: '')
          as String);
  @override
  bool get visibility =>
      (super.noSuchMethod(Invocation.getter(#visibility), returnValue: false)
          as bool);
  @override
  _i3.$RetailerDTOCopyWith<_i3.RetailerDTO> get copyWith =>
      (super.noSuchMethod(Invocation.getter(#copyWith),
              returnValue: _Fake$RetailerDTOCopyWith<_i3.RetailerDTO>())
          as _i3.$RetailerDTOCopyWith<_i3.RetailerDTO>);
  @override
  _i2.Retailer toDomain() =>
      (super.noSuchMethod(Invocation.method(#toDomain, []),
          returnValue: _FakeRetailer()) as _i2.Retailer);
  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(Invocation.method(#toJson, []),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
}

/// A class which mocks [RetailerListRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRetailerListRepository extends _i1.Mock
    implements _i5.RetailerListRepository {
  MockRetailerListRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.Either<_i7.FirestoreFailures, List<_i2.Retailer>>>
      getRetailerList() => (super.noSuchMethod(
          Invocation.method(#getRetailerList, []),
          returnValue: Future<
                  _i4.Either<_i7.FirestoreFailures, List<_i2.Retailer>>>.value(
              _FakeEither<_i7.FirestoreFailures, List<_i2.Retailer>>())) as _i6
          .Future<_i4.Either<_i7.FirestoreFailures, List<_i2.Retailer>>>);
}

/// A class which mocks [RetailerListState].
///
/// See the documentation for Mockito's code generation for more information.
class MockRetailerListState extends _i1.Mock implements _i8.RetailerListState {
  MockRetailerListState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  TResult when<TResult extends Object?>(
          {TResult Function()? initial,
          TResult Function()? loading,
          TResult Function(List<_i2.Retailer>)? loaded,
          TResult Function(String)? failure}) =>
      (super.noSuchMethod(
          Invocation.method(#when, [], {
            #initial: initial,
            #loading: loading,
            #loaded: loaded,
            #failure: failure
          }),
          returnValue: null) as TResult);
  @override
  TResult maybeWhen<TResult extends Object?>(
          {TResult Function()? initial,
          TResult Function()? loading,
          TResult Function(List<_i2.Retailer>)? loaded,
          TResult Function(String)? failure,
          TResult Function()? orElse}) =>
      (super.noSuchMethod(
          Invocation.method(#maybeWhen, [], {
            #initial: initial,
            #loading: loading,
            #loaded: loaded,
            #failure: failure,
            #orElse: orElse
          }),
          returnValue: null) as TResult);
  @override
  TResult map<TResult extends Object?>(
          {TResult Function(_i8.Initial)? initial,
          TResult Function(_i8.Loading)? loading,
          TResult Function(_i8.Loaded)? loaded,
          TResult Function(_i8.Failure)? failure}) =>
      (super.noSuchMethod(
          Invocation.method(#map, [], {
            #initial: initial,
            #loading: loading,
            #loaded: loaded,
            #failure: failure
          }),
          returnValue: null) as TResult);
  @override
  TResult maybeMap<TResult extends Object?>(
          {TResult Function(_i8.Initial)? initial,
          TResult Function(_i8.Loading)? loading,
          TResult Function(_i8.Loaded)? loaded,
          TResult Function(_i8.Failure)? failure,
          TResult Function()? orElse}) =>
      (super.noSuchMethod(
          Invocation.method(#maybeMap, [], {
            #initial: initial,
            #loading: loading,
            #loaded: loaded,
            #failure: failure,
            #orElse: orElse
          }),
          returnValue: null) as TResult);
}
