// Mocks generated by Mockito 5.0.12 from annotations
// in deall/test/core/infrastructure/retailer_dto_test.dart.
// Do not manually edit this file.

import 'package:deall/core/application/retailer/retailer.dart' as _i3;
import 'package:deall/core/infrastructure/retailer/retailer_dto.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _Fake$RetailerDTOCopyWith<$Res> extends _i1.Fake
    implements _i2.$RetailerDTOCopyWith<$Res> {}

class _FakeRetailer extends _i1.Fake implements _i3.Retailer {}

/// A class which mocks [RetailerDTO].
///
/// See the documentation for Mockito's code generation for more information.
class MockRetailerDTO extends _i1.Mock implements _i2.RetailerDTO {
  MockRetailerDTO() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(Invocation.getter(#id), returnValue: '') as String);
  @override
  String get name =>
      (super.noSuchMethod(Invocation.getter(#name), returnValue: '') as String);
  @override
  String get block =>
      (super.noSuchMethod(Invocation.getter(#block), returnValue: '')
          as String);
  @override
  String get street =>
      (super.noSuchMethod(Invocation.getter(#street), returnValue: '')
          as String);
  @override
  String get unit =>
      (super.noSuchMethod(Invocation.getter(#unit), returnValue: '') as String);
  @override
  String get postalCode =>
      (super.noSuchMethod(Invocation.getter(#postalCode), returnValue: '')
          as String);
  @override
  String get operatingHours =>
      (super.noSuchMethod(Invocation.getter(#operatingHours), returnValue: '')
          as String);
  @override
  String get description =>
      (super.noSuchMethod(Invocation.getter(#description), returnValue: '')
          as String);
  @override
  String get image =>
      (super.noSuchMethod(Invocation.getter(#image), returnValue: '')
          as String);
  @override
  bool get visibility =>
      (super.noSuchMethod(Invocation.getter(#visibility), returnValue: false)
          as bool);
  @override
  String get uen =>
      (super.noSuchMethod(Invocation.getter(#uen), returnValue: '') as String);
  @override
  _i2.$RetailerDTOCopyWith<_i2.RetailerDTO> get copyWith =>
      (super.noSuchMethod(Invocation.getter(#copyWith),
              returnValue: _Fake$RetailerDTOCopyWith<_i2.RetailerDTO>())
          as _i2.$RetailerDTOCopyWith<_i2.RetailerDTO>);
  @override
  _i3.Retailer toDomain() =>
      (super.noSuchMethod(Invocation.method(#toDomain, []),
          returnValue: _FakeRetailer()) as _i3.Retailer);
  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(Invocation.method(#toJson, []),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
}
